src/main/webapp/WEB-INF/view/admin/crawl/index.jsp
src/main/webapp/WEB-INF/view/admin/system/index.jsp

#288 crawl, system

---

src/main/webapp/WEB-INF/kibana/README.md
src/main/webapp/WEB-INF/kibana/fess_log.json

This file provides these visualizations
- search query counts / sec.
- average response time
- search term rank
- search term rank of no results
- hit counts
- rank of UserAgent

add dashboard settings for kibana4

---

src/main/java/org/codelibs/fess/api/json/JsonApiManager.java

JSON API for facet search

---

src/main/webapp/WEB-INF/orig/view/index.jsp
src/main/webapp/WEB-INF/view/index.jsp

Thank you for publish a awesome product 👍

Fix typo in class name

---

src/main/java/org/codelibs/fess/Constants.java
src/main/java/org/codelibs/fess/api/gsa/GsaApiManager.java
src/main/java/org/codelibs/fess/mylasta/direction/FessProp.java
src/main/resources/fess_api.xml

This API returns Google Search Appliance XML

support GSA API

---

src/main/java/org/codelibs/fess/entity/QueryContext.java

Fix geo API

---

src/main/java/org/codelibs/fess/app/service/ElevateWordService.java
src/main/webapp/WEB-INF/view/admin/elevateword/admin_elevateword_edit.jsp

Role suggest

---

src/main/webapp/WEB-INF/view/common/admin/sidebar.jsp
src/main/webapp/css/admin/style.css
src/main/webapp/css/style.css

UI is not displayed correctly

---

src/main/webapp/WEB-INF/crawler/resources/app.xml

fb2: org.apache.tika.parser.xml
ibooks, epub: org.apache.tika.parser.epub
http://tika.apache.org/1.13/formats.html#Text_formats

added book extensions fb2, ibooks, epub

---

src/main/webapp/WEB-INF/crawler/resources/app.xml

documents - extensions: odt
presentations->extensions: odp
(org.apache.tika.parser.odf)
http://tika.apache.org/1.13/formats.html#iWorks_document_formats

added OpenDocument Formats (Open Office)

---

src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java

* Use GitBucket's Get-Contents API for files (cf. https://github.com/gitbucket/gitbucket/pull/1320)
* Attach labels and roles to crawled documents

Some changes for GitBucketDataStoreImpl(#739)

---

src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java

**cf.** https://github.com/gitbucket/gitbucket/pull/1328

(refs #739) Use 'Accept' header when crawling GitBucket

---

src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java

This PR improves `GitBucketDataStoreImpl` to crawl GitBucket's issues and wiki.

Improve GitBucketDataStore for Issues and Wiki

---

src/main/java/org/codelibs/fess/app/web/admin/dataconfig/AdminDataconfigAction.java
src/main/java/org/codelibs/fess/app/web/admin/fileconfig/AdminFileconfigAction.java
src/main/java/org/codelibs/fess/app/web/admin/webconfig/AdminWebconfigAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/dataconfig/ApiAdminDataconfigAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/dataconfig/CreateBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/dataconfig/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/dataconfig/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileconfig/ApiAdminFileconfigAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileconfig/CreateBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileconfig/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileconfig/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/webconfig/ApiAdminWebconfigAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/webconfig/CreateBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/webconfig/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/webconfig/SearchBody.java

Add the following Admin APIs:
* #958 DataConfig
* #960 FileConfig
* #961 WebConfig

Implement Admin API: DataConfig, FileConfig, WebConfig

---

src/main/java/org/codelibs/fess/app/web/admin/duplicatehost/AdminDuplicatehostAction.java
src/main/java/org/codelibs/fess/app/web/admin/keymatch/AdminKeymatchAction.java
src/main/java/org/codelibs/fess/app/web/admin/labeltype/AdminLabeltypeAction.java
src/main/java/org/codelibs/fess/app/web/admin/log/AdminLogAction.java
src/main/java/org/codelibs/fess/app/web/api/ApiResult.java
src/main/java/org/codelibs/fess/app/web/api/admin/dataconfig/ApiAdminDataconfigAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/duplicatehost/ApiAdminDuplicatehostAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/duplicatehost/CreateBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/duplicatehost/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/duplicatehost/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileconfig/ApiAdminFileconfigAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/joblog/ApiAdminJoblogAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/joblog/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/joblog/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/keymatch/ApiAdminKeymatchAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/keymatch/CreateBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/keymatch/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/keymatch/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/labeltype/ApiAdminLabeltypeAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/labeltype/CreateBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/labeltype/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/labeltype/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/log/ApiAdminLogAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/webconfig/ApiAdminWebconfigAction.java

Implemented the following Admin APIs:
* #970 DuplicateHost 
* #973 LabelType
* #974 KeyMatch
* #975 JobLog
* #976 Log

Add several Admin APIs

---

src/main/java/org/codelibs/fess/app/web/admin/fileauth/AdminFileauthAction.java
src/main/java/org/codelibs/fess/app/web/admin/reqheader/AdminReqheaderAction.java
src/main/java/org/codelibs/fess/app/web/admin/webauth/AdminWebauthAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/crawlinginfo/ApiAdminCrawlinginfoAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/crawlinginfo/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/crawlinginfo/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/failureurl/ApiAdminFailureurlAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/failureurl/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/failureurl/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileauth/ApiAdminFileauthAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileauth/CreateBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileauth/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileauth/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/reqheader/ApiAdminReqheaderAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/reqheader/CreateBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/reqheader/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/reqheader/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/webauth/ApiAdminWebauthAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/webauth/CreateBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/webauth/EditBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/webauth/SearchBody.java

Implemented the following APIs:
* #964 crawlinginfo
* #971 failureurl
* #972 fiileauth
* #978 reqheader
* #981 webauth

Add Admin APIs

---

src/main/java/org/codelibs/fess/app/web/admin/backup/AdminBackupAction.java
src/main/java/org/codelibs/fess/app/web/admin/systeminfo/AdminSysteminfoAction.java
src/main/java/org/codelibs/fess/app/web/api/ApiResult.java
src/main/java/org/codelibs/fess/app/web/api/admin/backup/ApiAdminBackupAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/log/ApiAdminLogAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/systeminfo/ApiAdminSysteminfoAction.java

Implemented the following Admin API:
* #963 backup
* #980 systeminfo

Add Admin API: backup & systeminfo

---

src/test/java/org/codelibs/fess/it/admin/BoostDocTests.java

Add `BoostDocTests.java` for integration testing.

Add Integration Test for BoostDoc API

---

src/main/java/org/codelibs/fess/app/web/api/admin/dataconfig/ApiAdminDataconfigAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/dataconfig/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileconfig/ApiAdminFileconfigAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/fileconfig/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/webconfig/ApiAdminWebconfigAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/webconfig/SearchBody.java
src/test/java/org/codelibs/fess/it/CrudTestBase.java
src/test/java/org/codelibs/fess/it/admin/AccessTokenTests.java
src/test/java/org/codelibs/fess/it/admin/BoostDocTests.java
src/test/java/org/codelibs/fess/it/admin/DataConfigTests.java
src/test/java/org/codelibs/fess/it/admin/FileConfigTests.java
src/test/java/org/codelibs/fess/it/admin/WebConfigTests.java

* Refactor exsiting integration tests
* Add tests for #1019, #1029, #1044

Add Integration Tests (#1019, #1029, #1044)

---

src/main/java/org/codelibs/fess/app/web/admin/keymatch/CreateForm.java
src/main/java/org/codelibs/fess/app/web/api/admin/keymatch/ApiAdminKeymatchAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/keymatch/SearchBody.java
src/main/java/org/codelibs/fess/app/web/api/admin/labeltype/ApiAdminLabeltypeAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/labeltype/SearchBody.java
src/test/java/org/codelibs/fess/it/admin/AccessTokenTests.java
src/test/java/org/codelibs/fess/it/admin/BoostDocTests.java
src/test/java/org/codelibs/fess/it/admin/DataConfigTests.java
src/test/java/org/codelibs/fess/it/admin/FileConfigTests.java
src/test/java/org/codelibs/fess/it/admin/KeyMatchTests.java
src/test/java/org/codelibs/fess/it/admin/LabelTypeTests.java
src/test/java/org/codelibs/fess/it/admin/WebConfigTests.java

Integration tests for `keymatch`(#1033) and `labeltype`(#1034).

Add Integration Tests (#1033, #1034) 

---

src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java

* Fix #1058 
* Enable to store issue comments

Improve GitBucketDataStoreImpl

---

src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java

Fix #1063. (URL Encoding in GitBucketDataStore)

Fix issue 1063

---

src/test/java/org/codelibs/fess/it/admin/DuplicateHostTests.java
src/test/java/org/codelibs/fess/it/admin/GroupTests.java
src/test/java/org/codelibs/fess/it/admin/PathMapTests.java
src/test/java/org/codelibs/fess/it/admin/RoleTests.java

Add tests for #1025, #1031, #1036 and #1038.

Add Integration Tests (#1025, #1031, #1036, #1038) 

---

src/main/java/org/codelibs/fess/crawler/transformer/FessTransformer.java
src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java
src/test/java/org/codelibs/fess/crawler/transformer/FessFileTransformerTest.java

Improve GitBucketDataStore Crawler

---

pom.xml
src/main/java/org/codelibs/fess/app/web/api/admin/role/ApiAdminRoleAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/user/ApiAdminUserAction.java
src/test/java/org/codelibs/fess/it/CrudTestBase.java
src/test/java/org/codelibs/fess/it/admin/AccessTokenTests.java
src/test/java/org/codelibs/fess/it/admin/BoostDocTests.java
src/test/java/org/codelibs/fess/it/admin/DataConfigTests.java
src/test/java/org/codelibs/fess/it/admin/DuplicateHostTests.java
src/test/java/org/codelibs/fess/it/admin/FileAuthTests.java
src/test/java/org/codelibs/fess/it/admin/FileConfigTests.java
src/test/java/org/codelibs/fess/it/admin/GroupTests.java
src/test/java/org/codelibs/fess/it/admin/KeyMatchTests.java
src/test/java/org/codelibs/fess/it/admin/LabelTypeTests.java
src/test/java/org/codelibs/fess/it/admin/PathMapTests.java
src/test/java/org/codelibs/fess/it/admin/ReqHeaderTests.java
src/test/java/org/codelibs/fess/it/admin/RoleTests.java
src/test/java/org/codelibs/fess/it/admin/UserTests.java
src/test/java/org/codelibs/fess/it/admin/WebAuthTests.java
src/test/java/org/codelibs/fess/it/admin/WebConfigTests.java

* Refactoring for existing integration tests
* Add tests for Admin APIs (#1028, #1037, #1042, #1043)

Add Integration Tests (#1028, #1037, #1042, #1043)

---

src/main/java/org/codelibs/fess/app/web/api/ApiResult.java
src/main/java/org/codelibs/fess/app/web/api/admin/badword/ApiAdminBadwordAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/dict/ApiAdminDictAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/elevateword/ApiAdminElevatewordAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/systeminfo/ApiAdminSysteminfoAction.java
src/test/java/org/codelibs/fess/it/CrudTestBase.java
src/test/java/org/codelibs/fess/it/admin/BadWordTests.java
src/test/java/org/codelibs/fess/it/admin/ElevateWordTests.java
src/test/java/org/codelibs/fess/it/admin/GeneralTests.java
src/test/java/org/codelibs/fess/it/admin/SchedulerTests.java
src/test/java/org/codelibs/fess/it/admin/SuggestTests.java
src/test/java/org/codelibs/fess/it/admin/SystemInfoTests.java
src/test/java/org/codelibs/fess/it/admin/dict/DictCrudTestBase.java
src/test/java/org/codelibs/fess/it/admin/dict/DictTests.java

* #1017 /badword
* #1026 /elevateword
* #1039 /scheduler
* #1030 /general
* #1040 /suggest
* #1041 /systeminfo
* #1109 /dict

Add Integration Tests

---

README.md
src/main/java/org/codelibs/fess/app/web/api/admin/dict/mapping/ApiAdminDictMappingAction.java

Fixme: Return status 0 when request page doesn't exist.

Add page option for mapping API [WIP]

---

src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java

Since the master branch can be deleted, GitBucketDataStoreImple may not be able to crawl.
So use the default branch name returned by gitbucket-fess-plugin.
Notes
* Branch name is empty
* Skip as it is an empty git repository.
* Branch name parameter does not exist
* Since it is an old plugin, use the master branch.

Add branch params to GitBucketDataStoreImpl

---

src/test/java/org/codelibs/fess/it/ITBase.java
src/test/java/org/codelibs/fess/it/admin/CrawlerLogTests.java
src/test/java/org/codelibs/fess/it/admin/CrawlingInfoTests.java

Add integration tests that need web crawling.
* #1027 
* #1032 
* #1054 (partial)

Add Integration Tests: FailureUrl, JobLog

---

README.md

Signed-off-by: Stefan Weil <sw@weilnetz.de>

Update README.md (small grammar and typo fixes)

---

README.md
src/main/java/org/codelibs/fess/app/web/admin/searchlist/AdminSearchlistAction.java
src/main/java/org/codelibs/fess/app/web/admin/searchlist/CreateForm.java
src/main/java/org/codelibs/fess/app/web/admin/searchlist/EditForm.java
src/main/java/org/codelibs/fess/app/web/api/ApiResult.java
src/main/java/org/codelibs/fess/app/web/api/admin/searchlist/ApiAdminSearchlistAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/searchlist/SearchBody.java
src/main/java/org/codelibs/fess/mylasta/direction/FessConfig.java
src/main/java/org/codelibs/fess/mylasta/direction/FessProp.java
src/main/resources/fess_config.properties
src/test/java/org/codelibs/fess/it/CrudTestBase.java
src/test/java/org/codelibs/fess/it/admin/CrawlerLogTests.java
src/test/java/org/codelibs/fess/it/admin/SearchListTests.java
src/test/java/org/codelibs/fess/it/admin/dict/DictCrudTestBase.java
src/test/java/org/codelibs/fess/it/admin/dict/KuromojiTests.java
src/test/java/org/codelibs/fess/it/admin/dict/MappingTests.java
src/test/java/org/codelibs/fess/it/admin/dict/ProtwordsTests.java
src/test/java/org/codelibs/fess/it/admin/dict/SeunjeonTests.java
src/test/java/org/codelibs/fess/it/admin/dict/SynonymTests.java

* Add SearchList API (WIP)
* Fix /admin/dict/* APIs

Improve Integration Tests for Admin APIs

---

dbflute_fess/dfprop/_readme.txt
src/main/assemblies/files/fess
src/main/java/org/codelibs/fess/app/web/base/login/FessLoginAssist.java
src/main/java/org/codelibs/fess/es/config/allcommon/EsAbstractBehavior.java
src/main/java/org/codelibs/fess/es/log/allcommon/EsAbstractBehavior.java
src/main/java/org/codelibs/fess/es/user/allcommon/EsAbstractBehavior.java
src/main/java/org/codelibs/fess/mylasta/direction/FessEnv.java
src/main/resources/fess_env.properties
src/main/resources/fess_env_crawler.properties
src/main/resources/fess_env_suggest.properties
src/main/resources/fess_env_web.properties
src/main/webapp/js/admin/moment-with-locales.min.js
src/packaging/common/scripts/prerm

Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix some typos (most of them found by codespell)

---

src/test/java/org/codelibs/fess/it/admin/BackupTests.java
src/test/java/org/codelibs/fess/it/admin/JobLogTests.java
src/test/java/org/codelibs/fess/it/admin/LogTests.java
src/test/java/org/codelibs/fess/it/admin/SearchListTests.java

create BackupTests.java, JobLogTests.java, LogTests.java
update   SearchListsTests.java

Admin API Test : backup(#1016), joblog(#1032), log(#1035), searchlist(#1054)

---

src/main/webapp/js/help.js
src/main/webapp/js/search.js

I'm sorry, I made a mistake in the commit's comment.

update help.js and search.js

---

src/main/java/org/codelibs/fess/mylasta/action/FessLabels.java
src/main/resources/app.xml
src/main/resources/fess_label.properties
src/main/resources/fess_label_de.properties
src/main/resources/fess_label_en.properties
src/main/resources/fess_label_ja.properties
src/main/resources/fess_label_ko.properties
src/main/resources/fess_label_ru.properties
src/main/webapp/WEB-INF/env/crawler/resources/app.xml

https://github.com/codelibs/fess/issues/2245

#2245: Add mimetype:image/jpeg to the filetype facets

---

src/main/java/org/codelibs/fess/app/web/admin/storage/AdminStorageAction.java
src/main/java/org/codelibs/fess/app/web/admin/storage/ItemForm.java
src/main/java/org/codelibs/fess/mylasta/action/FessMessages.java
src/main/resources/fess_message.properties
src/main/webapp/WEB-INF/view/admin/storage/admin_storage.jsp

Add delete function #2319

---

src/main/java/org/codelibs/fess/app/web/admin/storage/AdminStorageAction.java
src/main/java/org/codelibs/fess/app/web/api/ApiResult.java
src/main/java/org/codelibs/fess/app/web/api/admin/storage/ApiAdminStorageAction.java
src/main/java/org/codelibs/fess/app/web/api/admin/storage/UploadForm.java
src/main/webapp/WEB-INF/view/admin/storage/admin_storage.jsp
src/test/java/org/codelibs/fess/it/admin/StorageTests.java

Add Admin API: /api/admin/storage #2333 

---

src/main/webapp/WEB-INF/view/admin/plugin/admin_plugin_installplugin.jsp

Fix #2383.<del>
Added `formaction` attribute to  use multiple submit buttons in an HTML `form`. 
</del><del>
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fs-formaction
https://www.w3schools.com/tags/att_button_formaction.asp
</del>
Rearraged buttons insted of using `formaction`.

Fix the Back button on /admin/plugin/installplugin #2383

---

src/main/webapp/WEB-INF/view/admin/backup/admin_backup.jsp
src/main/webapp/WEB-INF/view/admin/crawlinginfo/admin_crawlinginfo.jsp
src/main/webapp/WEB-INF/view/admin/dataconfig/admin_dataconfig.jsp
src/main/webapp/WEB-INF/view/admin/dataconfig/admin_dataconfig_edit.jsp
src/main/webapp/WEB-INF/view/admin/failureurl/admin_failureurl.jsp
src/main/webapp/WEB-INF/view/admin/log/admin_log.jsp
src/main/webapp/WEB-INF/view/admin/maintenance/admin_maintenance.jsp
src/main/webapp/WEB-INF/view/admin/plugin/admin_plugin.jsp
src/main/webapp/WEB-INF/view/admin/searchlog/admin_searchlog.jsp
src/main/webapp/WEB-INF/view/admin/storage/admin_storage.jsp
src/main/webapp/WEB-INF/view/admin/suggest/admin_suggest.jsp
src/main/webapp/WEB-INF/view/common/admin/header.jsp

* fix button message on card header on storage page
* delete `size="1"` on select tag
* `style="color:yellow"` -> `.text-warning` on header
* fix icons on mentenance page

Fix minor styles

---

src/main/webapp/WEB-INF/view/admin/boostdoc/admin_boostdoc.jsp
src/main/webapp/WEB-INF/view/admin/dataconfig/admin_dataconfig.jsp
src/main/webapp/WEB-INF/view/admin/duplicatehost/admin_duplicatehost.jsp
src/main/webapp/WEB-INF/view/admin/fileconfig/admin_fileconfig.jsp
src/main/webapp/WEB-INF/view/admin/keymatch/admin_keymatch.jsp
src/main/webapp/WEB-INF/view/admin/labeltype/admin_labeltype.jsp
src/main/webapp/WEB-INF/view/admin/pathmap/admin_pathmap.jsp
src/main/webapp/WEB-INF/view/admin/relatedcontent/admin_relatedcontent.jsp
src/main/webapp/WEB-INF/view/admin/relatedquery/admin_relatedquery.jsp
src/main/webapp/WEB-INF/view/admin/webconfig/admin_webconfig.jsp

Show the list search form if the search form is filled.

Improve List Search

---

.github/workflows/codeql-analysis.yml
.github/workflows/maven.yml
src/main/java/org/codelibs/fess/mylasta/direction/sponsor/FessMultipartRequestHandler.java
src/test/resources/before_script.sh
src/test/resources/run.sh

This refactor focuses on streamlining our GitHub Actions workflows for code analysis and Maven builds. Key changes include upgrading actions to their latest versions, simplifying the workflow configuration, and enhancing the readability and maintainability of our scripts. Specifically, we've updated the checkout and setup-java actions across all workflows to their v4 and adjusted the cache actions to v4, ensuring better cache management. Additionally, we've optimized the CodeQL workflow by refining the language matrix and updating the CodeQL action to v3 for improved security analysis. In our Maven workflow, similar updates to actions and JDK setup have been applied. Lastly, our test scripts have seen improvements for reliability and clarity, including better logging and error handling …

Refactor GitHub Actions for Improved Efficiency and Maintenance

---

src/main/java/org/codelibs/fess/ds/callback/FileListIndexUpdateCallbackImpl.java
src/main/java/org/codelibs/fess/helper/DocumentHelper.java

This pull request refactors how raw data and binary data are processed in the `FileListIndexUpdateCallbackImpl` and `DocumentHelper` classes by introducing the `DataSerializer` component. The changes improve code readability and modularity by replacing the use of `SerializeUtil` with `DataSerializer` for deserialization and adding logic to handle raw data when available.
* Replaced `SerializeUtil` with the `DataSerializer` component for deserializing binary data in both `FileListIndexUpdateCallbackImpl` and `DocumentHelper`. This change ensures consistency and modularity in the deserialization process. (`[[1]](diffhunk://#diff-e69e46a3a542b8931ff2e47b62b8922c8be4d1cc524dbd0d8bdf6f3d0f8f127bR241-R258)`, `[[2]](diffhunk://#diff-8448fff72e4cf4190db99b583711211dbb1e7a0d6062faa89b3baba4621602a6 …

Use DataSerializer for deserialization of ResultData in fallback path

---

src/main/java/org/codelibs/fess/ds/callback/FileListIndexUpdateCallbackImpl.java

This pull request introduces significant enhancements to the `FileListIndexUpdateCallbackImpl` class, focusing on improving crawling functionality by adding depth control, refactoring the URL queue to use a new `CrawlRequest` class, and enhancing error handling. Additionally, utility methods were added for better configuration management.
* Replaced the `Deque<String>` URL queue with a `Deque<CrawlRequest>` to manage both URLs and their corresponding depths. This allows for more granular control over the crawling process. (`src/main/java/org/codelibs/fess/ds/callback/FileListIndexUpdateCallbackImpl.java`, [src/main/java/org/codelibs/fess/ds/callback/FileListIndexUpdateCallbackImpl.javaR152-R266](diffhunk://#diff-e69e46a3a542b8931ff2e47b62b8922c8be4d1cc524dbd0d8bdf6f3d0f8f127bR152-R266))
* …

Add depth control for recursive file list crawling

---

src/main/java/org/codelibs/fess/mylasta/action/FessHtmlPath.java
src/main/java/org/codelibs/fess/mylasta/direction/FessConfig.java
src/main/java/org/codelibs/fess/opensearch/config/allcommon/EsAbstractBehavior.java
src/main/java/org/codelibs/fess/opensearch/log/allcommon/EsAbstractBehavior.java
src/main/java/org/codelibs/fess/opensearch/user/allcommon/EsAbstractBehavior.java
src/main/resources/fess_config.properties

This update enriches the fess_config.properties file with inline comments that explain the purpose of each configuration property. The enhancements cover all major configuration categories, such as:
- Core application settings
- Search engine connection and authentication
- JVM options for various processes
- Job execution parameters
- API, crawler, indexer, and query behavior
- Logging, online help, permissions, and more
The added comments aim to improve maintainability and reduce configuration errors by providing immediate contextual understanding for each property.

Add Descriptive Comments to fess_config.properties for Improved Configuration Clarity

---

pom.xml

Updated the parent POM version from 15.0.0-SNAPSHOT to 15.0.0 in pom.xml to reflect the official release version. This change finalizes the project versioning for the release.

Update parent POM version to 15.0.0

---

src/main/java/org/codelibs/fess/ds/callback/FileListIndexUpdateCallbackImpl.java
src/test/java/org/codelibs/fess/ds/callback/FileListIndexUpdateCallbackImplTest.java

This change introduces a mechanism to exclude specific URLs from crawling based on a user-defined regular expression pattern. A new constant URL_EXCLUDE_PATTERN is defined to identify the exclusion key in the parameter map. The method isUrlCrawlable checks the presence of the pattern and applies it to determine whether a URL should be skipped. The pattern is compiled once and cached for efficiency.

Add support for excluding URLs from crawling using a regex pattern

---

src/main/java/org/codelibs/fess/exec/ThumbnailGenerator.java
src/main/java/org/codelibs/fess/thumbnail/impl/CommandGenerator.java

This PR enhances the thumbnail generation logic by:
- Updating logging messages in ThumbnailGenerator for clarity.
- Adding error handling to CommandGenerator:
- Now returns exit codes from the command execution.
- Logs warnings if command execution fails.
- Deletes any potentially invalid output files upon failure.
- Providing a more detailed JavaDoc for the executeCommand method.
These changes aim to improve observability and robustness during thumbnail processing.

Improve Thumbnail Generation Logging and Error Handling
