codelibs/fess

src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java, src/main/resources/fess_ds.xml
This PR enables Fess to crawl repositories in a [GitBucket](https://github.com/gitbucket/gitbucket/) server with [Fess plugin](https://github.com/codelibs/gitbucket-fess-plugin/).
Expected parameters  in data store config are as follows:
```
url=http://yourgitbucket/
token=<TOKEN>
```
=> Crawler for GitBucket

src/main/java/org/codelibs/fess/crawler/transformer/FessTransformer.java, src/main/java/org/codelibs/fess/ds/impl/GitBucketDataStoreImpl.java, src/test/java/org/codelibs/fess/crawler/transformer/FessFileTransformerTest.java
The following problems remain in #1062. So I fixed it.
* URL encoding is not appropriate for a path containing a specific character. (Such as @ and space etc.)
* If the path contains `%23` (original letter is #), the URL is saved in the title tag.
**crawl log when including `@` in path** (origin path is `/node_modules/es5-ext/array/#/@@iterator`)
```
2017-05-29 04:46:41,918 [AVxNtQ7SteRxwqn425pe-1] WARN  Failed to access to http://127.0.0.1:8080/api/v3/repos/root/nodetest/contents/node_modules%2Fes5-ext%2Farray%2F%2523%2F%2540%2540iterator?ref=3d3cc5a17032b1d4c449e33480efcc31160f0ad5
org.codelibs.elasticsearch.runner.net.CurlException: The content does not exist.
at org.codelibs.elasticsearch.runner.net.CurlResponse.getContentAsStream(CurlResponse.java:62) …
```
=> Improve GitBucketDataStore Crawler

src/main/java/org/codelibs/fess/ds/impl/JsonDataStoreImpl.java, src/main/resources/fess_ds.xml
This is a JSON datastore implementation. It expects a JSON file with
one dict per line. It accepts the same common options as
CsvFileDataStore such as files, directories, and fileEncoding.
Example test.json:
```json
{"url": "http://google.com", "title": "Google"}
{"url": "http://github.com", "title": "Github"}
```
Example params:
```
files=/home/test/test.json
fileEncoding=utf-8
```
Example script:
```
url=url
title=title
```
=> JsonDataStore Implementation.

src/main/java/org/codelibs/fess/crawler/FessCrawlerThread.java, src/main/java/org/codelibs/fess/exception/ContentNotFoundException.java
This is necessary in order to easily determine where the bad URL came from
=> Added Parent URL to ContentNotFoundException

src/main/java/org/codelibs/fess/es/config/exentity/WebConfig.java, src/main/java/org/codelibs/fess/exec/Crawler.java, src/main/java/org/codelibs/fess/helper/LabelTypeHelper.java, src/main/java/org/codelibs/fess/helper/SystemHelper.java, src/test/java/org/codelibs/fess/helper/SystemHelperTest.java
Enhancement/feature to allow the use of "contains:" as a alternative to using RegEx. This is useful for when you have very many URLs to maintain and the paths are predefined. In addition, not everyone is familiar with RegEx and non programmers should be able to maintain the list of URLs to include/exclude and index. Lastly, it makes porting from GSA a lot simpler where you can just copy and paste collections to labels.
=> 'Contains' in addition to RegEx for path inclusion/exclusion

src/main/webapp/WEB-INF/orig/view/search.jsp, src/main/webapp/WEB-INF/view/search.jsp
Hi, developers. Thank you so much for your wonderful application!
I'm very new to Fess. The current Fess search result tells your search keywords to web servers you clicked. This PR makes Fess not to tell your search keywords to the web server by [Referrer-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) and improve privacy.
=> Set Referrer-Policy in search result

src/main/java/org/codelibs/fess/helper/IndexingHelper.java
When a crawler is re-executed with different permission settings, the crawler will create another set of results (with new permission settings).
But the older results (with old permission settings) are not properly removed.
This is reproducible on Fess 14.12.0-SNAPSHOT (codelibs/fess@613c418)
- Create 2 users (user1 and user2)
- Create a crawler (can be either Web, Filesystem or Datastore) with permission `{user}user1`
- Create and start the crawler's scheduler
- Change the crawler's permission to:
```
{user}user1
{user}user2
```
- Re-run the crawler's scheduler
Expected behavior: The older search results are removed and replaced with newer search results => searching by user1 only shows 1 result
Actual behavior: The newer search results are generated, but the older results still remain …
=> Search by DocID instead of ID when deleting old documents

.github/workflows/maven.yml, src/test/java/org/codelibs/fess/it/CrudTestBase.java, src/test/java/org/codelibs/fess/util/GsaConfigParserTest.java, src/test/resources/log4j2.xml
We've made significant updates to improve our CI/CD pipeline and test logging. Here's a summary of the changes:
1. Execution Environment Update: We've updated the .github/workflows/maven.yml file to switch our CI execution environment from ubuntu-latest to macos-14. This change ensures that our builds and tests have access to the necessary resources for efficient execution.
1. Enhanced Test Logging: To improve the visibility and troubleshooting capabilities of our testing process, we've introduced detailed logging in our test suite. Changes include logging at the beginning and end of test cases in CrudTestBase.java and GsaConfigParserTest.java, providing clear markers for test start and completion points. This aims to simplify identifying issues and understanding test flow.
1. Log …
=> Update Test Environment to macOS-14 and Enhance Logging During Test Execution

src/main/java/org/codelibs/fess/sso/oic/OpenIdConnectAuthenticator.java
Fixed issues that occurred when using single sign-on with AWS Cognito.
- Fixed an issue where users could not re-login.
- Fixed an issue where strings were not parsed correctly when jwtClaim contained an array type element.
- Improved to process all elements included in jwtClaim.
https://discuss.codelibs.org/t/openid-sso/2467
=> Fix sso oic OpenIdConnectAuthenticator

src/main/java/org/codelibs/fess/sso/oic/OpenIdConnectAuthenticator.java, src/test/java/org/codelibs/fess/sso/oic/OpenIdConnectAuthenticatorTest.java
Fixed an issue where the type of `attributes["groups"]` had changed from `String[]` to `List<Object>`. 
Add unittest.
fix #2845
=> bugfix OpenIdConnectAuthenticator

src/main/java/org/codelibs/fess/query/WildcardQueryCommand.java
This pull request improves the handling of highlighted queries in the `WildcardQueryCommand` class by introducing additional validation to ensure that only non-blank strings are added as highlighted queries. It also includes a minor import addition for utility functions.
* Updated `convertWildcardQuery` method to validate that the stripped query text is not blank before adding it as a highlighted query. This ensures that empty or whitespace-only strings are not unnecessarily processed. (`src/main/java/org/codelibs/fess/query/WildcardQueryCommand.java`, [[1]](diffhunk://#diff-066544c963089e7b9c4fb6a17a363535e93003ea53f3e2aa76bb8603c9f0e3a2L62-R77) [[2]](diffhunk://#diff-066544c963089e7b9c4fb6a17a363535e93003ea53f3e2aa76bb8603c9f0e3a2L85-R95)
* Added `StringUtil` import to leverage its …
=> Avoid adding blank highlight terms in WildcardQueryCommand

dbflute.xml, deps.xml, module.xml, plugin.xml, pom.xml, src/main/java/org/codelibs/fess/helper/IndexingHelper.java, src/main/java/org/codelibs/fess/mylasta/direction/FessProp.java, src/main/java/org/codelibs/fess/opensearch/client/CrawlerEngineClient.java, src/main/java/org/codelibs/fess/opensearch/client/SearchEngineClient.java, src/main/java/org/codelibs/fess/opensearch/config/allcommon/EsAbstractBehavior.java, src/main/java/org/codelibs/fess/opensearch/log/allcommon/EsAbstractBehavior.java, src/main/java/org/codelibs/fess/opensearch/user/allcommon/EsAbstractBehavior.java, src/main/java/org/codelibs/fess/query/BooleanQueryCommand.java, src/main/java/org/codelibs/fess/query/DefaultQueryBuilder.java, src/main/java/org/codelibs/fess/query/parser/QueryParser.java, src/main/java/org/codelibs/fess/rank/fusion/DefaultSearcher.java, src/main/java/org/codelibs/fess/thumbnail/impl/HtmlTagBasedGenerator.java, src/main/java/org/codelibs/fess/util/UpgradeUtil.java, src/test/java/org/codelibs/fess/helper/QueryHelperTest.java, src/test/java/org/codelibs/fess/query/parser/QueryParserTest.java
This pull request includes updates to migrate from older versions of Fess and OpenSearch to newer versions, along with associated dependency and configuration updates. Key changes include updating branch and version references, modifying Maven repository URLs, removing deprecated modules, and addressing API changes in OpenSearch. Below is a summary of the most important changes grouped by theme:
* Updated branch references in `dbflute.xml` and `deps.xml` to `fess-15.0` and `fess-15`, respectively, reflecting the migration to the latest version. (`[[1]](diffhunk://#diff-83ac3473fe2fd2f92f726e4b94ac06498ae1da610bc268051f07e1cdfceac4a7L5-R5)`, `[[2]](diffhunk://#diff-cf596639fa506105d26e89c53d79c0b1c10ccda1e0f65b1e66b23046176644b7L9-R12)`)
* Upgraded OpenSearch version from `2.19.1` to …
=> Complete migration of Fess to OpenSearch 3.0 APIs and infrastructure

src/main/java/org/codelibs/fess/helper/UserInfoHelper.java, src/test/java/org/codelibs/fess/helper/UserInfoHelperTest.java
This pull request enhances cookie security handling in the `UserInfoHelper` class and adds corresponding unit tests to ensure the functionality works as expected. The key changes include introducing a method to determine if cookies should be secure and updating the logic for setting cookie security attributes.
* [`src/main/java/org/codelibs/fess/helper/UserInfoHelper.java`](diffhunk://#diff-80017b1a9f69f6c2e00337785023c31b86ca5c4739ea0423780d1c459c58cbbfR153-R168): Added a new method `isSecureCookie()` to determine if cookies should be marked as secure. The method checks the `cookieSecure` property and falls back to inspecting the `X-Forwarded-Proto` header or the request's security status. Updated the `updateCookie` method to use `isSecureCookie()` and ensure cookies are added to the …
=> Refactor cookie security logic using isSecureCookie method

src/main/resources/fess_indices/fess.json
This pull request updates the configuration for the Japanese tokenizer in the `fess.json` file to simplify its setup by removing the reloadable feature.
Tokenizer configuration changes:
* [`src/main/resources/fess_indices/fess.json`](diffhunk://#diff-177fdc6c8217b6866de849798156568f50371252d7f22e5cb29536e49cb2e2c9L660-R663): Changed the Japanese tokenizer type from `fess_japanese_reloadable_tokenizer` to `fess_japanese_tokenizer` and removed the `reload_interval` property.
=> Refactor Japanese tokenizer configuration in fess.json

src/main/java/org/codelibs/fess/ds/callback/FileListIndexUpdateCallbackImpl.java, src/test/java/org/codelibs/fess/ds/callback/FileListIndexUpdateCallbackImplTest.java
This PR refactors how responseDataMap is merged into dataMap in FileListIndexUpdateCallbackImpl. Instead of directly using putAll, a new method mergeResponseData is introduced to support special handling of keys ending with .overwrite. These keys will override corresponding base keys after removing the .overwrite suffix, improving the flexibility of data merging logic.
=> Enhance data map merging with overwrite key handling in FileListIndexUpdateCallbackImpl

src/main/resources/fess_indices/_aws/fess.json, src/main/webapp/WEB-INF/view/admin/general/admin_general.jsp
This pull request updates the Korean tokenizer configuration in the AWS-specific index settings by switching from seunjeon_tokenizer to nori_tokenizer with appropriate settings to align with the current OpenSearch capabilities.
=> Update AWS index settings and hide unsupported options for cloud/AWS in admin UI

plugin.xml
This update replaces the opensearch-analysis-fess plugin version from 3.0.0 to 3.0.1 in plugin.xml. It ensures compatibility with the latest plugin release and incorporates any bug fixes or improvements provided in the newer version.
=> Update opensearch-analysis-fess plugin to version 3.0.1

dbflute.xml, module.xml, plugin.xml, pom.xml
This update includes the following changes:
- Upgraded branch.name in dbflute.xml from fess-15.0 to fess-15.1.
- Bumped opensearch.version in module.xml from 3.0.0 to 3.1.0.
- Updated multiple plugin versions in plugin.xml to 3.1.0, including:
- analysis-extension
- analysis-fess
- configsync
- minhash
- Updated pom.xml:
- Changed project version from 15.0.1-SNAPSHOT to 15.1.0-SNAPSHOT.
- Updated parent POM version to 15.1.0-SNAPSHOT.
These changes prepare the project for compatibility with the latest Fess 15.1 and OpenSearch 3.1.0 versions.
=> Update Fess and OpenSearch to version 15.1 and 3.1.0 respectively

src/main/java/org/codelibs/fess/mylasta/action/FessLabels.java, src/main/java/org/codelibs/fess/mylasta/action/FessMessages.java, src/main/resources/fess_message.properties, src/main/resources/fess_message_de.properties, src/main/resources/fess_message_en.properties, src/main/resources/fess_message_fr.properties, src/main/resources/fess_message_ko.properties, src/main/resources/fess_message_ru.properties
This pull request adds the missing errors.unauthorized_request message to all supported language resource files (fess_message.properties, fess_message_en.properties, fess_message_de.properties, fess_message_fr.properties, fess_message_ko.properties, and fess_message_ru.properties). This ensures consistent error message handling for unauthorized request scenarios across different locales.
=> Add missing errors.unauthorized_request message to all language resource files

src/main/java/org/codelibs/fess/app/web/base/FessSearchAction.java, src/main/java/org/codelibs/fess/app/web/sso/SsoAction.java, src/main/java/org/codelibs/fess/entity/RequestParameter.java, src/main/java/org/codelibs/fess/helper/SearchHelper.java, src/main/java/org/codelibs/fess/mylasta/direction/FessConfig.java, src/main/resources/fess_config.properties, src/test/java/org/codelibs/fess/helper/SearchHelperTest.java
This pull request enhances the SSO login flow by introducing functionality to store and restore search parameters using cookies. Key additions include:
- SearchHelper now serializes selected request parameters into a compressed and encoded cookie before redirecting to login.
- On successful login, these parameters are retrieved and appended to the search redirect URL.
- New methods storeSearchParameters() and getSearchParameters() were implemented in SearchHelper.
- Configuration keys were added to FessConfig and fess_config.properties to support cookie attributes (e.g., name, max age, secure, SameSite).
- Adjustments in FessSearchAction and SsoAction to integrate the parameter preservation and restoration flow.
This improves user experience by maintaining their search context across SSO …
=> Preserve and Restore Search Parameters Using Cookies in SSO Flow

src/main/java/org/codelibs/fess/helper/SystemHelper.java, src/test/java/org/codelibs/fess/helper/ActivityHelperTest.java, src/test/java/org/codelibs/fess/helper/CrawlerStatsHelperTest.java, src/test/java/org/codelibs/fess/helper/CrawlingConfigHelperTest.java, src/test/java/org/codelibs/fess/helper/CrawlingInfoHelperTest.java, src/test/java/org/codelibs/fess/helper/CurlHelperTest.java, src/test/java/org/codelibs/fess/helper/DataIndexHelperTest.java, src/test/java/org/codelibs/fess/helper/IndexingHelperTest.java, src/test/java/org/codelibs/fess/helper/JobHelperTest.java, src/test/java/org/codelibs/fess/helper/KeyMatchHelperTest.java, src/test/java/org/codelibs/fess/helper/LabelTypeHelperTest.java, src/test/java/org/codelibs/fess/helper/LanguageHelperTest.java, src/test/java/org/codelibs/fess/helper/OsddHelperTest.java, src/test/java/org/codelibs/fess/helper/PathMappingHelperTest.java, src/test/java/org/codelibs/fess/helper/PluginHelperTest.java, src/test/java/org/codelibs/fess/helper/PopularWordHelperTest.java, src/test/java/org/codelibs/fess/helper/ProcessHelperTest.java, src/test/java/org/codelibs/fess/helper/ProtocolHelperTest.java, src/test/java/org/codelibs/fess/helper/QueryHelperTest.java, src/test/java/org/codelibs/fess/helper/RelatedContentHelperTest.java, src/test/java/org/codelibs/fess/helper/RelatedQueryHelperTest.java, src/test/java/org/codelibs/fess/helper/RoleQueryHelperTest.java, src/test/java/org/codelibs/fess/helper/SambaHelperTest.java, src/test/java/org/codelibs/fess/helper/SearchHelperTest.java, src/test/java/org/codelibs/fess/helper/SearchLogHelperTest.java, src/test/java/org/codelibs/fess/helper/SuggestHelperTest.java, src/test/java/org/codelibs/fess/helper/SystemHelperTest.java, src/test/java/org/codelibs/fess/helper/ThemeHelperTest.java, src/test/java/org/codelibs/fess/helper/ViewHelperTest.java, src/test/java/org/codelibs/fess/helper/VirtualHostHelperTest.java
This pull request includes two main changes:
1. Refactoring in SystemHelper:
- The getUsername() method now uses a protected getRequestManager() method. This refactor facilitates better testability and decoupling, enabling easier mocking or overriding of request handling behavior in test contexts.
2. Test Cleanup Enhancements:
- Added or updated tearDown() methods across all test classes to explicitly reset FessConfig using ComponentUtil.setFessConfig(null).
- This change ensures test isolation and prevents interference from shared static configuration states.
- Additionally, redundant imports and commented-out legacy code in test classes were removed for clarity.
These changes improve the maintainability and reliability of the test suite and support more consistent unit test behavior.
=> Refactor SystemHelper and Standardize Test Teardown for FessConfig Cleanup

src/test/java/org/codelibs/fess/crawler/transformer/FessFileTransformerTest.java, src/test/java/org/codelibs/fess/crawler/transformer/FessXpathTransformerTest.java, src/test/java/org/codelibs/fess/helper/CrawlerStatsHelperTest.java, src/test/java/org/codelibs/fess/helper/CrawlingConfigHelperTest.java, src/test/java/org/codelibs/fess/helper/IndexingHelperTest.java, src/test/java/org/codelibs/fess/helper/JobHelperTest.java, src/test/java/org/codelibs/fess/helper/KeyMatchHelperTest.java, src/test/java/org/codelibs/fess/helper/LabelTypeHelperTest.java, src/test/java/org/codelibs/fess/helper/LanguageHelperTest.java, src/test/java/org/codelibs/fess/helper/OsddHelperTest.java, src/test/java/org/codelibs/fess/helper/ProtocolHelperTest.java, src/test/java/org/codelibs/fess/helper/QueryHelperTest.java, src/test/java/org/codelibs/fess/helper/RelatedContentHelperTest.java, src/test/java/org/codelibs/fess/helper/RelatedQueryHelperTest.java, src/test/java/org/codelibs/fess/helper/RoleQueryHelperTest.java, src/test/java/org/codelibs/fess/helper/SambaHelperTest.java, src/test/java/org/codelibs/fess/helper/SearchHelperTest.java, src/test/java/org/codelibs/fess/helper/SearchLogHelperTest.java, src/test/java/org/codelibs/fess/helper/SuggestHelperTest.java, src/test/java/org/codelibs/fess/helper/SystemHelperTest.java, src/test/java/org/codelibs/fess/helper/ThemeHelperTest.java, src/test/java/org/codelibs/fess/helper/ViewHelperTest.java, src/test/java/org/codelibs/fess/helper/VirtualHostHelperTest.java, src/test/java/org/codelibs/fess/query/TermQueryCommandTest.java, src/test/java/org/codelibs/fess/util/ComponentUtilTest.java
This update removes unnecessary tearDown() method overrides from multiple test classes across the codebase. These overrides previously called ComponentUtil.setFessConfig(null), which is no longer required due to improved container lifecycle handling or updated mocking behavior. The cleanup reduces test code redundancy and simplifies maintenance without affecting test behavior.
=> Remove redundant tearDown() overrides in test classes

src/main/java/org/codelibs/fess/helper/SystemHelper.java
This pull request updates the end-of-life (EOL) date for Fess version 15.1.0 in the SystemHelper class.
The EOL date has been changed to January 1, 2027 to reflect the revised support policy.
=> Update EOL date for Fess 15.1.0

.gitignore, module.xml, plugin.xml, src/main/java/org/codelibs/fess/helper/SystemHelper.java, src/main/java/org/codelibs/fess/opensearch/client/SearchEngineClient.java, src/test/java/org/codelibs/fess/thumbnail/impl/CommandGeneratorTest.java, src/test/java/org/codelibs/fess/timer/SystemMonitorTargetTest.java
This PR introduces several updates across different modules:
- **SystemHelper**
- Updated the EOL date from **January 1, 2027** to **March 1, 2027**.
- Minor formatting fix for missing newline at end of file.
- **SearchEngineClient**
- Added a new `prepareStreamSearch` method with JavaDoc, delegating to the underlying client.
- **CommandGeneratorTest**
- Reformatted initialization of `invalidParent` for better readability and consistency.
- **SystemMonitorTargetTest**
- Improved the `test_expired_method_can_be_called` test:
- Avoids strict dependency on system environment.
- Ensures the method can be invoked without compilation/runtime signature issues.
- Logs exceptions instead of failing tests when system dependencies are missing.
=> Update EOL date, add stream search support, and improve test robustness

src/main/java/org/codelibs/fess/helper/PermissionHelper.java, src/main/java/org/codelibs/fess/helper/SambaHelper.java, src/test/java/org/codelibs/fess/helper/SambaHelperTest.java
I've updated the JCIFS library import paths throughout the codebase to align with the new library structure from org.codelibs.jcifs.
- Updated `PermissionHelper.java` to use `org.codelibs.jcifs.smb.SID` instead of `jcifs.SID`
- Updated SMB1 specific imports to use `org.codelibs.jcifs.smb1.SID` for legacy SMB1 compatibility
- Modified `SambaHelper.java` to use the new import paths
- Updated `SambaHelperTest.java` to import `org.codelibs.jcifs.smb.impl.SmbException` for proper exception handling
- Verified that all import statements resolve correctly
- Ensured SID type handling remains consistent across both SMB and SMB1 protocols
- Checked that existing permission and Samba helper functionality is preserved
None - This is an internal refactoring that maintains the same public API.
This …
=> Fix: Update JCIFS library import paths

plugin.xml
I updated the Maven release repository URL in `plugin.xml` from the deprecated Sonatype OSS URL to the current Maven Central repository URL. This ensures proper dependency resolution and compatibility with Maven Central's current infrastructure.
- Updated `maven.release.repo.url` property in `plugin.xml`
- Changed from `https://oss.sonatype.org/content/repositories/releases` to `https://repo1.maven.org/maven2`
The old Sonatype OSS URL has been deprecated. Maven Central now uses `repo1.maven.org/maven2` as the canonical repository URL. This change ensures:
- Reliable dependency resolution
- Compatibility with current Maven Central infrastructure
- Alignment with Maven best practices
- Verified the URL is the correct Maven Central repository endpoint
- This is a configuration-only change …
=> fix(build): Update Maven repository URL to Maven Central
